### PR TITLE
Made it easier to read/check the output by formatting it with newlines and indentation

### PR DESCRIPTION
**Pull request by Bitblade**
It does add some bytes to the output size, but I think the readability / verifiability is preferable.

### CODE REVIEW

**Comment by Bitblade** [comment]
Also: 
Corrected the elements used when setting BIC to NOTPROVIDED

The Rabobank (Dutch bank) requires the BIC to be provided or to be set
to NOTPROVIDED.

**Comment by JelleM-Congressus** [comment]
I am currently looking into providing better readabillity (protip: open with a browser like firefox will format automatically). However I will NOT allow NOTPROVIDED as BIC. It is simply not schema compliant and if we start accepting every strange option that individual banks require it will (unfortunately) become one big mess. The bank is included in the IBAN however and for dutch banks calculating the BIC from the IBAN is very trivial. If you need a conversion list please contact me.

**Comment by Heart1010** [comment]
As of Feb 2016 we don't have to use any BIC numbers, means we can send payments wit only the IBAN number (ibanonly). And afaik when using ibanonly there has to be that NOTPROVIDED tag in the xml!!?

**Comment by JelleM-Congressus** [comment]
I agree with not having to provide a BIC, but if you set the BIC to NOTPROVIDED you go against the official xsd. The correct way would be not setting the BIC node (even though the xsd does not like that also). The current best way is to just provide a BIC calculated from the IBAN. Its not a library fault afaik but more of a thing with the banks. If you still really want this, you can remove the BIC check yourself and always provide NOTPROVIDED as BIC.

-------- Origineel bericht --------
Van:Hermann Herz <notifications@github.com>
Verzonden:Sat, 09 Jan 2016 07:11:04 +0100
Aan:congressus/sepa-direct-debit <sepa-direct-debit@noreply.github.com>
Cc:Jelle van der Molen <jelle@congressus.nl>
Onderwerp:Re: [sepa-direct-debit] Made it easier to read/check the output by formatting it with newlines and indentation (#20)

**Comment by Bitblade** [comment]
I fear you misunderstood what this patch does. 

ISO 20022 requires the ```<FinInstnId>``` tag to have at least one of the following elements: 
* ```<BICFI>```
* ```<ClrSysMmbld>```
* ```<Nm>```
* ```<PstlAdr>```
* ```<Othr>```

Currently, If BIC information is provided, it is assumed to be BICFI information. (Assuming xsd version 3 or above). For a valid BIC code, this leads to the following structure:
```
<DbtrAgt>
    <FinInstnId> 
        <BICFI>BBBBCCLL[bbb]</BICFI>
    </FinInstnld>
</DbtrAgt>
```
_(Note: The library does in fact consider NOTPROVIDED a valid BIC code since it is only tested using a regex)_

However, when not providing a BIC code, the structure should be (according to ISO 20022):
```
<DbtrAgt>
    <FinInstnId> 
        <Othr>
            <Id>NOTPROVIDED</Id>
        </Othr>
    </FinInstnld>
</DbtrAgt>
```

My patch makes sure the correct structure is used when the BIC code is set to NOTPROVIDED. This is in fact fully compliant with the xsd.

**Comment by JelleM-Congressus** [comment]
Ah I see, in that case you are correct, however I think it would be more wise to use NOTPROVIDED as a case for a missing BIC (thus, not providing a BIC will lead to NOTPROVIDED with the <Othr><Id> tags.) Do you agree?

**Comment by JelleM-Congressus** [comment]
Implemented your suggestions :)

**Pull request closed without merging**
